#define BACKLIGHT_BREATHING
#define TAPPING_TERM 170
#define PERMISSIVE_HOLD
#define AUTO_SHIFT_TIMEOUT 170
#define TAPPING_TERM_PER_KEY
#define GRAVE_ESC_CTRL_OVERRIDE
#define DYNAMIC_MACRO_NO_NESTING

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 5000
